CREATE TABLE [dbo].[Playlists](
	[Playlist_ID] [int] IDENTITY(10000,1) NOT NULL,
	[PlayList_Number] [int] NOT NULL,
	[TrackNumber] [int] NOT NULL,
	[PlaylistTrackNumber] [INT] NOT NULL,
	[TrackName] [VARCHAR](MAX) NULL,
	[ArtistName] [VARCHAR](MAX) NULL,
	[PlayListName] [VARCHAR](MAX) NULL,
	[PlayListID] [VARCHAR](MAX) NULL,
	[TrackExternalURL] [VARCHAR](MAX) NULL,
	[TrackSpotifyAPI] [VARCHAR](MAX) NULL,
	[TrackAddedDate] [VARCHAR](MAX) NULL,
	[AddedBy_ID] [VARCHAR](MAX) NULL,
	[RUN_ID] [VARCHAR](150) NULL,
	[Added_To_Table_Date_Time] [VARCHAR](MAX) NULL)
